# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [1]:
import numpy as np
array = np.random.randint(1, 100, (10, 10))
print("\nСозданный массив: \n\n", array)
print("\nМинимальное значение:", array.min())
print("Максимальное значение:", array.max())


Созданный массив: 

 [[57 65 80 39 79 68 14 17 49 40]
 [63 91  1 98 44 60  5 81 96 12]
 [52 10 60 81 77 39 93 72 88 69]
 [85 89 99 85 67 93 25 73 78 41]
 [ 4 35 80 37 41 78 61 46 91 10]
 [73  3 15 56 92 30 53 73 92 60]
 [94 17 53 63 93 61  4 90 84 13]
 [79 17 51 95 19 64 73 84 57 18]
 [ 5 46 54 19 21  3 49  2 48 51]
 [65 55 33 27 69 64 65 17 34 68]]

Минимальное значение: 1
Максимальное значение: 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [2]:
import numpy as np
matrix = np.zeros((8,8))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print("Матрица 8х8 в шахматном порядке: \n", matrix)

Матрица 8х8 в шахматном порядке: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [3]:
import numpy as np
x = np.arange(11)
print("Исходный массив:\n", x)
x[(x > 3) & (x < 8)] *= -1
print("\nИзмененный массив:\n", x)

Исходный массив:
 [ 0  1  2  3  4  5  6  7  8  9 10]

Измененный массив:
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [4]:
import numpy as np
z = np.random.rand(5, 10)
print("Матрица: \n", z)
means = np.mean(z, axis=1, keepdims=True)
z[:, :9] -= means
print("\nСреднее значение:\n", means)
print("\nИзмененная матрица:\n", z)

Матрица: 
 [[0.34708163 0.41822741 0.83615834 0.21708467 0.4249012  0.64869756
  0.71019624 0.45165552 0.54512568 0.20341482]
 [0.48809582 0.31897172 0.70948539 0.39544486 0.51222856 0.89611819
  0.03218889 0.56016089 0.99916805 0.78831684]
 [0.09641704 0.6927236  0.62871281 0.10394427 0.92064948 0.18099575
  0.54000937 0.59296623 0.96148753 0.19765871]
 [0.39124859 0.31679683 0.2491521  0.4984449  0.7965533  0.90732401
  0.68398438 0.78908195 0.0051704  0.94760744]
 [0.70985082 0.15136564 0.89789497 0.75655781 0.98813436 0.59388351
  0.55566797 0.3708477  0.47252717 0.12494889]]

Среднее значение:
 [[0.48025431]
 [0.57001792]
 [0.49155648]
 [0.55853639]
 [0.56216789]]

Измененная матрица:
 [[-0.13317268 -0.06202689  0.35590404 -0.26316964 -0.0553531   0.16844325
   0.22994193 -0.02859879  0.06487137  0.20341482]
 [-0.0819221  -0.2510462   0.13946747 -0.17457306 -0.05778936  0.32610027
  -0.53782903 -0.00985703  0.42915013  0.78831684]
 [-0.39513943  0.20116712  0.13715633 -0.38761221 

5. Поменяйте 1 и 2 строки матрицы

In [5]:
import numpy as np
z = np.arange(25).reshape(5,5)
print("Матрица:\n", z)
z[[1, 2]] = z[[2, 1]]
print("\nИзмененная матрица:\n", z)

Матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Измененная матрица:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [6]:
import numpy as np
z = np.random.random((10, 2))
print("Декартова система координат:\n", z)
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
phi = np.arctan2(y, x)
pz = np.column_stack((r, phi))
print("\nПолярные координаты:\n", pz)

Декартова система координат:
 [[0.33659525 0.13392111]
 [0.71199928 0.82281031]
 [0.91183131 0.32967394]
 [0.32912729 0.85572751]
 [0.02951051 0.43499308]
 [0.5271488  0.66218559]
 [0.46645007 0.7550951 ]
 [0.02106855 0.27388118]
 [0.10465823 0.13967062]
 [0.41793004 0.62146534]]

Полярные координаты:
 [[0.36225851 0.37866871]
 [1.08809916 0.85747166]
 [0.9695985  0.34692836]
 [0.91683932 1.20362115]
 [0.43599295 1.5030588 ]
 [0.84638975 0.89845381]
 [0.88754959 1.017437  ]
 [0.27469034 1.49402164]
 [0.17453145 0.92772949]
 [0.74892235 0.97877211]]


7. Заменить максимальный элемент массива на ноль

In [7]:
import numpy as np
z = np.random.random(10)
print("Массив:\n", z)
max = np.argmax(z)
print("\nИндекс максимального элемента:", max)
z[max] = 0
print("\nИзмененный массив:\n", z)

Массив:
 [0.42404121 0.88350521 0.73131148 0.88257585 0.11109477 0.17490271
 0.66814576 0.43728367 0.86982816 0.95332119]

Индекс максимального элемента: 9

Измененный массив:
 [0.42404121 0.88350521 0.73131148 0.88257585 0.11109477 0.17490271
 0.66814576 0.43728367 0.86982816 0.        ]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [8]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print("Массив:\n", z)
print("\nМассив индексов:\n", i)
unique = np.unique(i)
z[unique] += 1
print("\nИзмененный массив:\n", z)

Массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Массив индексов:
 [9 0 3 1 6 4 6 8 0 0 7 3 4 9 2 0 3 2 2 6]

Измененный массив:
 [2. 2. 2. 2. 2. 1. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [9]:
import numpy as np
z = np.array([1,2,3,4,5])
print("Вектор:\n", z)
x = np.zeros(len(z) + (len(z) - 1) * 3)
x[::4] = z
print("\nНовый вектор:\n", x)

Вектор:
 [1 2 3 4 5]

Новый вектор:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [10]:
import numpy as np
z = np.arange(100)
v = np.random.uniform(0,100)
print("Массив:\n", z)
print("\nЗаданное значение:", v)
x = np.fabs(z - v).argmin()
y = z[x]
print("\nБлижайшее значение для", v, "=", y)

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Заданное значение: 99.79575746430861

Ближайшее значение для 99.79575746430861 = 99


## Вопросы




# Ответы на вопросы

## 1. Какой тип (dtype) будут иметь элементы массива?
```python
import numpy as np

# Типы данных массивов
print(np.array([1, 4, 2, 5, 3]).dtype)  # int64 или int32 (зависит от системы)
print(np.array([1., 4, 2, 5, 3]).dtype)  # float64
print(np.array([1, 4, 2, 5, 3], dtype='float128').dtype)  # float128
print(np.array([1., 4, 2, 5, 3], dtype='complex128').dtype)  # complex128
print(np.array([1, 4, 2, 5, 3], dtype='float64').dtype)  # float64
print(np.array([1, 4, 2, 5, 3], dtype='int64').dtype)  # int64
print(np.array([1, 4, 2, 5, 3], dtype='bool').dtype)  # bool
print(np.array([1, 4, 2, 5, 3], dtype='str').dtype)  # <U1
print(np.array([1, 4, 2, 5, '3']).dtype)  # <U21 (строки)
print(np.array([1, -4, 2, 0, 1j]).dtype)  # complex128


**2**. Что будет выведено в консоль и почему?
- Операции с массивами
```python
print(np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1')  # '41'
print(np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1])  # -4
print(np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1])  # False
print(np.array([1, -4, 2, 0, True], dtype='int64')[-1])  # 1
print(np.array([1, -4, 2, 0, 1j], dtype='str')[-1])  # '1j'
print(np.array([1, 4, 2, 5, '3'])[-1] * 3)  # '333'


**3**. Каков результат операции?

``` python
print(np.ones((3, 5), dtype=float))  # Матрица 3x5 из 1.0
print(np.full((3, 5), 3.14))  # Матрица 3x5 из 3.14
print(np.linspace(0, 1, 5))  # [0. , 0.25, 0.5 , 0.75, 1. ]
print(np.diag((1, 3, 5)))  # Диагональная матрица с диагональю [1, 3, 5]
print(np.random.random((3, 3)))  # Матрица 3x3 со случайными значениями
print(np.eye(3))  # Единичная матрица 3x3
print(np.empty(3))  # Пустой массив из 3 элементов (значения не инициализированы)


**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
print(X[0, 0])  # 3
print(X[-1, -1])  # 7
print(X[0:1, -1])  # [4]
print(X[0:2, -1])  # [4, 8]
print(X[0:2, 0:2])  # [[3, 5], [7, 6]]
print(X[1, 1:3])  # [6, 8]
print(X[1, :])  # [7, 6, 8, 8]
print(X[:, :])  # Весь массив
print(X[::2, ::2])  # [[3, 2], [1, 7]]
print(X[::-1, ::-1])  # Обратный массив
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
print(np.split(grid, [2]))  # Разделение по строкам
print(np.split(grid, [2], axis=1))  # Разделение по столбцам


**6**. В чем различие между операциями?

``` python
print([1, 2, 3] + [3, 2, 1])  # Конкатенация списков: [1, 2, 3, 3, 2, 1]
print(np.array([1, 2, 3]) + np.array([3, 2, 1]))  # Покомпонентное сложение: [4, 4, 4]


**7**. Как в CodeLab измерить время выполнения кода?  
```python
# Используем магическую команду %%time
%%time
result = sum(range(1000000))


**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])

print(np.sum(X))  # Сумма всех элементов
print(np.sum(X, axis=1))  # Сумма по строкам
print(np.sum(X, axis=0))  # Сумма по столбцам


**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1, 2, 3, 4])

print(X > 3)  # [False False False True]
print(X < 3)  # [ True  True False False]
print(X[X < 3])  # [1 2]
print(X[X > 3])  # [4]
print(X[X != 3])  # [1 2 4]


**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?  

**Преимущества:**
- 1. Быстрее, так как операции выполняются на уровне C (ближе к железу).
- 2. Меньше памяти, поскольку тип элементов массива фиксирован.
- 3. Мощные инструменты для работы с большими данными (трансформации, вычисления, индексация).
